### ISSUE TITLE
Invitation to move to testing-library org

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/testcafe-testing-library#1]
It's up to you, but if you'd like, you're welcome to transfer this repository to the [testing-library organization on GitHub](https://github.com/testing-library). This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by kentcdodds** [comment]
FYI, this library has gotten a mention in our big announcement today: https://testing-library.com/blog/2019/04/25/new-org :)

**Comment by benmonro** [comment]
@all-contributors please add @kentcdodds for infrastructure, ideas and code

**Comment by benmonro** [comment]
@kentcdodds Ok, I'm ready to transfer ownership.  I think I need to be given permission.  :)

**Comment by kentcdodds** [comment]
Sweet, you've been invited! https://github.com/testing-library

**Comment by benmonro** [comment]
done.  🎉
