### ISSUE TITLE
Does testcafe-testing-library support IE11

### ISSUE THREAD

**Issue by kkateli** [testing-library/testcafe-testing-library#126]
I have used testcafe-testing-library on chrome/firefox/IE11. Chrome and Firefox all work fine but I am having these errors on IE11:

An error occurred in Selector code: 
 TypeError: Unable to get property 'apply' of undefined or null reference

An error occurred in a script injected into the tested page:
 TypeError: Unable to get property 'for' of undefined or null reference

I am wondering if testcafe-testing-library supports IE browser?

My Test:
test('Show title', async t => {
  await t
    .expect(getByText('title').visible)
    .ok('Title is visible.');
});

**Comment by benmonro** [comment]
@kkateli it has not been tested on ie11, but would welcome a PR if you want to address that.

**Comment by benmonro** [comment]
For anyone interested in order to support ie 11 you would need to provide shims for Dom testing library which doesn't ship with any right now so will not work in ie11

**Comment by edouard-lopez** [comment]
Damn! 
I started to explore `testcafe` for the sole purpose of protecting against regression in IE11 :S

By shim do you mean something like [`core-js`](https://github.com/zloirock/core-js) ?
I reckon it's still possible to test without `testcafe-testing-library`
