### ISSUE TITLE
testcafe-testing-library breaks TestCafe's testController.navigateTo function.

### ISSUE THREAD

**Issue by SamuelDavis** [testing-library/testcafe-testing-library#222]
**Describe the bug**
If the testcafe-testing-library script has been injected into the browser, when TestCafe runs and attempts to invoke the `testController.navigateTo` method, the following error is thrown:
> TypeError: Cannot read property 'destUrl' of null
Of course, the stack trace terminates at the invocation point in the test script rather than where `destUrl` is actually referenced.

If I follow the [docs](https://testing-library.com/docs/testcafe-testing-library/intro#usage) exactly, the full error is...
> An error occurred in the '@testing-library/dom/dist/@testing-library/dom.umd.js' module injected into the tested page. Make sure that this module can be executed in the browser environment.
> 
> Error details:
> 
> TypeError: Cannot read property 'destUrl' of null

If I modify the .testcaferc.json to not inject the script as a module then I get...
> An error occurred in a script injected into the tested page:
> 
>  TypeError: Cannot read property 'destUrl' of null

**To Reproduce**
Please see [this repo](https://github.com/SamuelDavis/testing-library-testcafe-integration) which is the minimal-reproducible-example I could create.
1. ```git clone git@github.com:SamuelDavis/testing-library-testcafe-integration.git;```
2. ```cd testing-library-testcafe-integration;```
3. ```npm install;```
4. ```npx testcafe chrome tests.js;``` or via docker: ```docker run --rm -it -v $PWD:/mnt -w /mnt --env NODE_PATH=/mnt/node_modules testcafe/testcafe chromium tests.js;```

**Expected behavior**
I expect the test to pass, or at least throw an error relevant to the test I've written, or provide me with more actionable feedback.

**Screenshots**
![testcafe-testing-library failing](https://user-images.githubusercontent.com/2657052/89227341-7f4b8100-d5ab-11ea-8553-7c2d247e53cd.png)

**Additional context**
It seems like it might be an underlying issue with testcafe-hammerhead.js, but the error only occurs when the testcafe-testing-library script is injected. It's also significant that the [usage docs](https://testing-library.com/docs/testcafe-testing-library/intro#usage) .testcaferc.json module configuration throws an error out of the box.

**Comment by benmonro** [comment]
strange, I use navigateTo all the time but haven't run into this.

would love a PR if you'd like to contribute a bug fix.  the library is pretty small, basically just a wrapper over dom testing library.

otherwise i will try to look into this either tonight or tomorrow.

**Comment by SamuelDavis** [comment]
@benmonro Thanks for the fast response. It's over my head; I'd appreciate another set of eyes on my example repo. Even if the problem isn't specifically in this repo, I posted the issue here simply because following the usage docs fails out of the box as far as I can tell. If it can't be fixed here then I'd appreciate a recommendation as to where the issue belongs: maybe testing-library/dom, maybe testcafe-hammerhead? Let me know what you think and thanks again.

**Comment by benmonro** [comment]
no problem, busy at the moment but will try to look tonight.  in the meantime, if you find anything out let me know!

**Comment by benmonro** [comment]
@SamuelDavis I think I found your problem.  your fixture has no page.  In testcafe, when you use the clientScripts feature you have to have some page.  I don't think there's anything that we can do in this library to account for that since the clientScripts are statically defined in the config.  If it's a problem you can open an issue in testcafe's issue tracker to let them know.  otherwise, for now if you change your code to have a `.page` then navigateTo should work just fine.  

```js

fixture("foo").page("https://google.com")

```

let me know if that works for you, but I have to close this issue since it's ultimately an issue in testcafe and the way they handle clientScripts.

**Comment by SamuelDavis** [comment]
@benmonro You're absolutely right; thanks so much.
