### ISSUE TITLE
Error: TypeScript compilation failed.

### ISSUE THREAD

**Issue by mwq27** [testing-library/testcafe-testing-library#232]
**Describe the bug**
After adding testcafe-testing-library to my project, I'm getting a TS compilation error: 
```
.../node_modules/@testing-library/testcafe/dist/index.d.ts (2, 13): '=' expected.
.../node_modules/@testing-library/testcafe/dist/index.d.ts (2, 77): ';' expected.
```

**To Reproduce**
1. Add testcafe-testing-library to project
2. Execute a test
3. See error

**Expected behavior**
Test should run

**Screenshots**
![Screen Shot 2020-08-19 at 9 50 24 AM](https://user-images.githubusercontent.com/551359/90650382-6ecd1480-e201-11ea-82ce-0929e94ba399.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version 84

**Additional context**
I have TS@3.9.7, TestCafe@1.9.1

**Comment by benmonro** [comment]
@mwq27 i use the library with typescript but don't have this problem. Would you mind sharing a reproducible example of this?

**Comment by benmonro** [comment]
@mwq27 closing for now but if you can provide an example repro we can re open

**Comment by nilshartmann** [comment]
fyi: I had the same problem using TypeScript 3.x; upgrading to TypeScript 4.x solved the problem.

**Comment by nickmccurdy** [comment]
Perhaps TypeScript 4 should be added to peerDependencies?
