### ISSUE TITLE
TypeError: Cannot read property 'destUrl' of null

### ISSUE THREAD

**Issue by kevin-inrupt** [testing-library/testcafe-testing-library#250]
**Describe the bug**
After including a reference to `"@testing-library/dom/dist/@testing-library/dom.umd.js"` in `.testcaferc.json` as per https://testing-library.com/docs/testcafe-testing-library/intro, tests that were successfully executing now fail with error:

```
- Error in fixture.beforeEach hook -
An error occurred in the '@testing-library/dom/dist/@testing-library/dom.umd.js' module injected into the tested page. Make sure that this module can be executed in the browser environment.

Error details:
TypeError: Cannot read property 'destUrl' of null

Browser: Microsoft Edge 85.0.564.51 / Windows 10

6 |
7 |/// Login/Logout workflow
8 |fixture('Login/Logout')
9 |    .beforeEach( async t => {
10 |        await t
> 11 |            .useRole(nssUser);
12 |    });
13 |
14 |/// Login & Logout
15 |test
16 |    ("Log user into & out of PodBrowser", async t => {

at <anonymous> (C:\Projects\GitHub\destURL\tests\login.js:11:14)
at <anonymous> (C:\Projects\GitHub\destURL\tests\login.js:8:1)
```

**To Reproduce**
1. Extract the attached zipfile [destURL.zip](https://github.com/testing-library/testcafe-testing-library/files/5227357/destURL.zip)
2. Execute `testcafe edge ./tests/login.js`.

**Expected behavior**
Login test passes.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Version 85.0.564.51 (Official build) (64-bit)

**Comment by benmonro** [comment]
@kevin-inrupt when you say it was working but now it's not... Can you give more details?  How was it working before without the reference?

Also what version of the library are you using?

**Comment by kevin-inrupt** [comment]
+ testcafe@1.9.2
+ @testing-library/testcafe@4.2.2

The only change that I made to my full test suite was to include the following in the `.testcaferc.json` file:
```
    "clientScripts": [
        { "module": "@testing-library/dom/dist/@testing-library/dom.umd.js" }
    ],
```

Prior to the change, the tests executed successfully. After the change, the tests failed to execute and the error shown in the description was displayed in the console.

In the cut-down sample test attached to the bug, the same issue is displayed:

- Without `clientScipts` update, the login.js single test executes and types `https://dev.inrupt.com` into the dropdown.
- With `clientScripts` update, the error is displayed when the browser is loading.

_This issue seems very similar to https://github.com/testing-library/testcafe-testing-library/issues/164._

**Comment by benmonro** [comment]
@kevin-inrupt can you try adding `.page` to your fixture?  I believe there's a bug in testcafe where you have to specify `.page` if you're using clientScripts in this way.

**Comment by kevin-inrupt** [comment]
@benmonro That looks like it fixed it - at least there are no errors when starting up a test. Just need to see if there is a way of rewriting the tests/roles so there are not 2 page loads.

Many thanks for the prompt help.

**Comment by benmonro** [comment]
What we did recently is have a hand shake mode so nothing is rendered by the app until the hand shake is complete.  Alternatively you could create a blank page as a starting page so at least the videos don't look choppy.  But it's it's annoying.  Feel free to post a bug to test Cafe.  I'll be happy to +1 it.  🙂

**Comment by kevin-inrupt** [comment]
Based on your suggestion, create https://github.com/DevExpress/testcafe/issues/5555

**Comment by benmonro** [comment]
Thank you!
