### ISSUE TITLE
Type Error:  Argument of type '{ name: string; }' is not assignable to parameter of type 'MatcherOptions'.

### ISSUE THREAD

**Issue by timmak** [testing-library/testcafe-testing-library#251]
**Describe the bug**
The issues is in the types file options argument not all option take the base interface MatcherOptions some take extend options as seen here https://github.com/testing-library/dom-testing-library/blob/master/types/queries.d.ts

**To Reproduce**
```
import { getByRole, within } from "@testing-library/testcafe";

getByRole("cell", { name: `test` })
```
**Expected behavior**
The option types should match those queires in dom testing library

**Comment by benmonro** [comment]
@timmak  are you on the latest version?

We are using the matcher options from DTL as you can see here: https://github.com/testing-library/testcafe-testing-library/blob/master/src/types.ts#L6

**Comment by timmak** [comment]
*ByRole uses a extended matcher of MatchOptions 
https://github.com/testing-library/dom-testing-library/blob/master/types/queries.d.ts#L69

Unless I am missing reading it, and using the latest version

**Comment by benmonro** [comment]
Ah good catch definitely a bug.  Would you mind submitting a PR to fix it?
