### ISSUE TITLE
Error: Cannot call method 'getByPlaceholderText' of undefined

### ISSUE THREAD

**Issue by Srihari88** [testing-library/testcafe-testing-library#263]
**Describe the bug**
I am trying to execute the below sample code and it's always throwing the same error that Cannot call method 'getByPlaceholderText' of undefined. Attached the code below. 

import {
    getByText,
    getByPlaceholderText
  } from '@testing-library/testcafe'

fixture('Google Page').page('https://opensource-demo.orangehrmlive.com/index.php/auth/login');

test("Create button", async t => {

    await t.typeText(getByPlaceholderText('Username'),'admin');
    await t.typeText(getByPlaceholderText('Password'),'admin123')
    await t.click(getByText('LOGIN'))
});

**Screenshots**
<img width="836" alt="Screenshot 2020-11-24 at 10 23 06 PM" src="https://user-images.githubusercontent.com/12937252/100126296-c8e61180-2ea3-11eb-86d9-6742ddc42667.png">

**Comment by benmonro** [comment]
@Srihari88 is it possible for you to post a repository with this problem in a reproducible state?

**Comment by Srihari88** [comment]
it's working. after uninstall & install this library
