### ISSUE TITLE
After reload inside of a test error "TestingLibraryDom is not defined" thrown.

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [testing-library/testcafe-testing-library#28]
Adding testcafe-testing-library to fixture,

```
fixture`Foo`
  .page(constants.base)
  .beforeEach(addTestcafeTestingLibrary);
```

If I reload the page during a test I get an error thrown when I use a testcafe-testing-library functions in the same test.

```
await t.eval(() => location.reload(true));
await t
    .expect(getAllByTestId("foo")).ok()
```

Error thrown,

![image](https://user-images.githubusercontent.com/50481613/63256206-ff7bb800-c26e-11e9-920d-b60d54b5929a.png)

**Comment by rssfrncsrenishaw** [comment]
Interestingly if I manually add after the reload it works...

```
await t.eval(() => location.reload(true));
  await addTestcafeTestingLibrary(t)
  await t
    .expect(getAllByTestId("foo")).ok()
```

This is not ideal.

**Comment by benmonro** [comment]
Thanks for reporting!  I will look into this

**Comment by rssfrncsrenishaw** [comment]
I posted it on stackoverflow and was told to look into https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.html

**Comment by benmonro** [comment]
Yes they just added that feature.  The fix will probably involve that

**Comment by benmonro** [comment]
@rssfrncsrenishaw feel free to give this issue a 👍 as it will help fix your problem cleanly. :)
https://github.com/DevExpress/testcafe/issues/4176

**Comment by benmonro** [comment]
@rssfrncsrenishaw I have released a new version (3.0.0) that should support your issue.  The breaking changes are that addTestcafeTestingLibrary has been removed in favor of clientScripts which is now supported in testcafe 1.4.x.

To test this, you will need to update to testcafe 1.4.x (if you haven't already) and then do `npm i -D @testing-library/testcafe@next`

**Comment by rssfrncsrenishaw** [comment]
nice work!

**Comment by benmonro** [comment]
Does that mean it works for you?  🙂

**Comment by rssfrncsrenishaw** [comment]
Unable to upgrade to 1.4.X at the moment so can't test it...

**Comment by benmonro** [comment]
ok, well I added a test for your use case and the new client script injection should fix this, so closing for now, but if you do run into issues again feel free to reopen.  

Fixed in https://github.com/testing-library/testcafe-testing-library/releases/tag/v3.0.0%40next
