### ISSUE TITLE
Upgrading to 3.x broken previously working tests.

### ISSUE THREAD

**Issue by mbulfair** [testing-library/testcafe-testing-library#36]
I upgraded following https://testing-library.com/docs/testcafe-testing-library/intro

Removing:
`addTestcafeTestingLibrary` from my test and beforeEach in the fixture.

Adding:
```js
  "clientScripts": [
    "./node_modules/@testing-library/dom/dist/@testing-library/dom.umd.js"
  ],
```
With a very simple test:

```js
test('Table Exists', async t => {
  await getByTestId('table-id').exists;
});
```

Now I get:
```
   1) Selector cannot implicitly resolve the test run in context of which it should be executed. If you need to call Selector from the Node.js API callback, pass
      the test controller manually via Selector's `.with({ boundTestRun: t })` method first. Note that you cannot execute Selector outside the test code.
```

I have others' but, this is the simplest example. If I downgrade to 2.x it works as expected, did I miss something?

**Comment by benmonro** [comment]
Are you on version 1.5 or greater of testcafe?

**Comment by benmonro** [comment]
Also what happens when that is in a t.expect?

**Comment by mbulfair** [comment]
Yes I was on all the latest versions per the documentation. I am just checking if the element is present. This is a react project.

**Comment by mbulfair** [comment]
```json
    "@testing-library/dom": "^6.4.1",
    "@testing-library/jest-dom": "^4.1.0",
    "@testing-library/react": "^9.2.0",
    "@testing-library/testcafe": "^2.1.1",
```

**Comment by benmonro** [comment]
Ok and what if you wrap it in t.expect?

Any chance you could push a repro to a repo somewhere?

**Comment by mbulfair** [comment]
I can't share the code directly, under corporate github. 

I have the clientScripts in my testcaferc.json file
Here's the test:

```
test('User Table Exists', async t => {
  await t.expect(getByTestId('table-users').exists).ok();
});
```

The screenshot shows the page to now be blank and the error is saying it can't find the element. (Which I would expect) given that, which is the best way to have the test wait, it's a react project but I think that module conflicts in some way with this upgrade.

**Comment by benmonro** [comment]
so just to confirm, does wrapping the call in `t.expect` get rid of the error for you?

re: the react project / conflicts, I'd have to get more details/error messages.  I use this on react projects all the time, it really shouldn't conflict w/ anything since it's testing the full running app.

**Comment by mbulfair** [comment]
Right, I upgraded all at once all the testcafe related things, including adding requestmocks, and this error kept happening. So far I think it's ok. Sorry for the issue.

**Comment by benmonro** [comment]
@mbulfair no worries.  Glad it worked out.  Hope you enjoy using TCTL.  I welcome and and all feedback/issues/PRs. 🙂
