### ISSUE TITLE
Babel 6 errors when using react-boilerplate

### ISSUE THREAD

**Issue by Ronva** [testing-library/testcafe-testing-library#37]
Using testcafe-testing-library with react-boilerplate causes this error: 
```js
ERROR Cannot prepare tests due to an error.

ReferenceError: Using removed Babel 6 option: .resolveModuleSource - Use `babel-plugin-module-resolver@3`'s 'resolvePath' options
```

Steps to reproduce:
1. Set up a react-boilerplate project (https://github.com/react-boilerplate/react-boilerplate/#quick-start).
2. Install `testcafe` and `@testing-library/testcafe` as dependencies.
3. Create a test file and add a test that uses a helper function from `@testing-library/testcafe`.
4. Run the test with testcafe.

Unfortunately I couldn't get this work on codesandbox but here is a reproduction repo (just run the `testcafe` script):
https://github.com/Ronva/react-boilerplate-testcafe
Relevant changes: https://github.com/Ronva/react-boilerplate-testcafe/commit/bc1e5c5a4a379635953cd723a8e3a740d7a9e821

**Comment by benmonro** [comment]
Thank you @Ronva i will look into this on the weekend... my only time these days for open source fun. :)

**Comment by benmonro** [comment]
@Ronva it looks like your project was missing a .testcaferc.json file.  I will make it more clear in the docs that this is required.  I opened a PR on your example.  let me know if that fixes your issues.  if not please let me know what versions of node, npm etc you are using when you run this.

here's the PR showing what works on my machine: https://github.com/Ronva/react-boilerplate-testcafe/pull/1/files

**Comment by benmonro** [comment]
@Ronva closing this since you said in the PR that is working for you but feel free to reopen.
