### ISSUE TITLE
Unpredictable assertion behaviour in highly async application

### ISSUE THREAD

**Issue by feclist** [testing-library/testcafe-testing-library#85]
Hi 👋

We're using TestCafe in combination with testcafe-testing-library to test our highly async Electron app. I am encountering this problem where assertions like:
` t.expect(queryAllByText('Surrey Quays').nth(8).exists).ok()`
Sometimes fail and sometimes pass. I came across an older already closed issue (#53), covering a similar problem where slower apps do funny things using `get*` instead of `query*`. 

Now, that made sense to me as `get*` throws and `query*` returns. Since a lot of items in our app appear in an asynchronous manner, that would've and should've solved our problem. Sadly enough I am still seeing these random assertion failures. 

It could be that I'm missing a step or that I'm using the assertions wrong. In any circumstance, I would like to see if I can get my tests to work in a predictable manner :)

Cheers

**Comment by benmonro** [comment]
Hi @feclist can you provide a repo with reprodicible example so I can take a look?

**Comment by feclist** [comment]
Hi @benmonro , thanks for the quick reply. I'll have to look into reproducing this error. I'll try and get something together over the weekend such that you can get a look at it.

My suspicion, however, is that it has to do with the `nth(8).exists` causing retries not to happen (I can be way off here as I haven't dug into the source code yet). The behaviour I see when running the tests is that it fails straightaway without showing the `Waiting for element` in the TestCafe frame.

Anyway, I'll try and make a reproducible repo over the weekend for you to look at :).

**Comment by benmonro** [comment]
@feclist any update on this?

**Comment by feclist** [comment]
@benmonro I've tried to create a reproduction of the problem we're experiencing. Haven't been able to do so yet, sadly enough. I would need to look into it deeper, but don't think I'll have time to do so soon..

Would be fine to close this issue, unless you would have any suggestions as to where this issue could come from.

**Comment by benmonro** [comment]
Hmm. Hard to say to be honest but I can give some tips for debugging.  If you use the t.debug() feature of testcafe then you can go into the browser and manually run `TestingLibDom.getByText(document.body, "hello")` to see what's happening as that is what testcafe-testing-library does under the hood.

I should also note that getBy should not be used with async. Only queryBy.  Also of note in testcafe-testing-library findBy is an alias of queryBy due to the built in waiting mechanism that testcafe provides

**Comment by benmonro** [comment]
I'll close this issue for now but if you can provide a repro I'm happy to reopen it
